[package]
name = "dante-server"
version = "0.1.0"
edition = "2024"

[dependencies]
choki = "1.1.14"
dotenv = "0.15.0"
rand = "0.9.1"
serde = "1.0.219"
serde_json = "1.0.140"


[dependencies.mongodb]
version = "3.2.3"
features = ["sync"]
